### ISSUE TITLE
Nav bar be buttons?

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#106]
Should the navbar be made of buttons @aakashpatel1 and @aacarroll ? I don't know what you're doing with GUI... I was just thinking if it were something besides a hyperlink it could be dynamically changed. For example, login switches to logout after successfully authenticated, etc. 

Just curious. Teach me your marvelous GUI ways!

**Comment by Ma1iciousL0af** [comment]
I had a navbar template that I have locally. I'll push it to GUIoverhaul when I get a chance and let me know what you think.

Sent from my iPhone

On Apr 17, 2015, at 1:34 PM, AlyssaR <notifications@github.com<mailto:notifications@github.com>> wrote:

Should the navbar be made of buttons @aakashpatel1https://github.com/aakashpatel1 and @aacarrollhttps://github.com/aacarroll ? I don't know what you're doing with GUI... I was just thinking if it were something besides a hyperlink it could be dynamically changed. For example, login switches to logout after successfully authenticated, etc.

Just curious. Teach me your marvelous GUI ways!

##

**Comment by quincyschurr** [comment]
@aacarroll  I like this!!!
