### ISSUE TITLE
Register Account - Password Check

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#108]
It checks the password through javascript as soon as you click the input field. It should wait until you have clicked submit.

**Comment by AlyssaR** [comment]
Fixed this.

**Comment by cknee217** [comment]
I have found another issue with this. When you try to register and type in a password the password field for logging in highlights in green.

![screen shot 2015-04-19 at 3 08 58 pm](https://cloud.githubusercontent.com/assets/8548541/7221164/4871b2fc-e6a6-11e4-8b34-fe8cd168c2e1.png)

**Comment by AlyssaR** [comment]
Oops. My bad. Reopening.

**Comment by AlyssaR** [comment]
No longer a problem with new gui.
