### ISSUE TITLE
[17] Font API

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#112]
Integrate Google Fonts API to make things pretty.

**Comment by KristoforHorst** [comment]
Pushed, everything should be RALEWAY font now. Someone confirm you see that? @AlyssaR @aacarroll

**Comment by AlyssaR** [comment]
Confirmed that our site was Fontified.

**Comment by KristoforHorst** [comment]
Closing the gate, or something.
