### ISSUE TITLE
Register Account - need to check email validation

### ISSUE THREAD

**Issue by cknee217** [AlyssaR/StudyNetwork#115]
need to check how it validates that a user is using an SMU email

![screen shot 2015-04-19 at 9 08 38 am](https://cloud.githubusercontent.com/assets/8548541/7219742/4bb22050-e674-11e4-8d27-37812072de15.png)

**Comment by quincyschurr** [comment]
You mean this?

![screen shot 2015-04-19 at 9 18 00 am](https://cloud.githubusercontent.com/assets/8551481/7219767/036ad606-e675-11e4-94af-d320cbd9465f.png)

**Comment by cknee217** [comment]
That code must not be working properly. When I entered my SMU email I still got the error message

**Comment by quincyschurr** [comment]
Looks like with all the bootstrap changes the js calls aren't always being called.

**Comment by AlyssaR** [comment]
It was being called, but the validEmail and validPass functions get the fields by id (either email or password). Problem was that with the new site design the login box is on every page, so there are multiple inputs with the same id and it was validating the wrong one. I renamed the ids to be unique and tweaked the functions a bit so they don't alert on a bad password until you submit. About to also fix the color change that shows matching passwords.

**Comment by AlyssaR** [comment]
fixed password match/color thing too. @cknee217 @quincyschurr
