### ISSUE TITLE
Pulling Organizations

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#116]
Writing API function to get the Organizations a member is involved in to print to profile.html

**Comment by quincyschurr** [comment]
Functionality for multiple Orgs or singular is done, waiting js verification. On branch doWork

**Comment by quincyschurr** [comment]
Java Script now works for adding an organization. Still need to get this to the website

**Comment by quincyschurr** [comment]
This works - can also leave class. Just need someone to test once merged to dev

**Comment by AlyssaR** [comment]
@quincyschurr can't leave class. Other stuff works.

**Comment by quincyschurr** [comment]
@AlyssaR closing because there is already an issue for classes that is separate.
