### ISSUE TITLE
WHERE LIKE Functionality

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#160]
Want to great API so results with similar names to that searched will appear

**Comment by quincyschurr** [comment]
waiting for verification on this with JS

**Comment by AlyssaR** [comment]
*clarification please - what verification are you waiting on? @quincyschurr

**Comment by quincyschurr** [comment]
To see if the JS is pulling similar results instead of exact

**Comment by quincyschurr** [comment]
This works. Closing.
