### ISSUE TITLE
Register account, not allowing login

### ISSUE THREAD

**Issue by cgutsch08** [AlyssaR/StudyNetwork#168]
I think this best explained in pictures.
I register my account, and I'm welcomed.
![screen shot 2015-04-26 at 12 03 35 am](https://cloud.githubusercontent.com/assets/8550114/7335967/0fd51fcc-eba8-11e4-8f71-b1e20ae43564.png)

Redirects me to home(?) page, with error that I'm not logged in.

![screen shot 2015-04-26 at 12 03 51 am](https://cloud.githubusercontent.com/assets/8550114/7335968/0fd5d8ae-eba8-11e4-9ed5-6127d8a39b18.png)

I click "okay", and it brings me to image 3...

![screen shot 2015-04-26 at 12 04 05 am](https://cloud.githubusercontent.com/assets/8550114/7335969/0fd78f14-eba8-11e4-94eb-ed4b66cbae7d.png)

And when I click "the study network" link on far left, I'm redirected to the second image and it starts over again, endlessly. I can stop it by logging out or closing the browser, but I can't actually log in after registering the account WITHOUT logging out of undefined. Perhaps an auto log in to the new account would be appropriate?

**Comment by AlyssaR** [comment]
@cgutsch08 - I was attempting to fix this so you could continue testing, but I am unable to reproduce it. Could you verify that after registering (when it says "Welcome, Cal"), you have a session cookie? You can do this through add-ons, or also through developer tools in your browser. In Chrome, it's under "Resources" > "Cookies". It won't say "dev", but the cookie name should still be StudyNetwork. 
![howtofindcookies](https://cloud.githubusercontent.com/assets/6731550/7339269/a52a8d9c-ec2e-11e4-9b7a-bc4d5a10d4e0.PNG)

**Comment by AlyssaR** [comment]
I found the issue and tracked it back to an API error. Would you mind testing again to see if you have the same problem? @cgutsch08

**Comment by williamoconnor** [comment]
I get the problem still

And mine doesn't fix when I close the browser, so I guess I am done testing haha

**Comment by AlyssaR** [comment]
What browser are you using, @williamoconnor ? I've tested in Firefox and Chrome (as have others) and it works for us. One member couldn't get it to work in Safari, so that might be the issue?

**Comment by williamoconnor** [comment]
Chrome

**Comment by williamoconnor** [comment]
I just tried again, and this is still the case

**Comment by cgutsch08** [comment]
Sorry, I just saw these notifications in my email. It's fixed for me. I register, and it takes me to my profile page.

**Comment by AlyssaR** [comment]
@williamoconnor can you give me more information on what you're trying to register with? I'd like to check and see if the account was ever successfully added to our database.

**Comment by AlyssaR** [comment]
Confirmed to be fixed.
