### ISSUE TITLE
Search Relevance

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#169]
- Not logged in
- Using 'SearchByGroup'
  -Search term: 'Syndicate' (also used 'sup' and 'I don't 'understand' with similarly random results)

![screen shot 2015-04-27 at 10 29 46 am](https://cloud.githubusercontent.com/assets/5313865/7351079/a453b4ee-ecc8-11e4-992d-5aa9e5ee2060.png)
- Using 'SearchByOrganization'
- Search term: 'Cincinnati'
  ![screen shot 2015-04-27 at 10 33 04 am](https://cloud.githubusercontent.com/assets/5313865/7351115/da3581e6-ecc8-11e4-8f91-34a2c78d3b8b.png)

**Comment by KristoforHorst** [comment]
Closed. Sorted relevance by highest members first.
