### ISSUE TITLE
Class names appear to be times and meeting times are places

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#170]
I'm just confused, this is probably just a labelling issue
![screen shot 2015-04-27 at 10 34 38 am](https://cloud.githubusercontent.com/assets/5313865/7351139/071f275c-ecc9-11e4-9fe6-fc0116c49221.png)

**Comment by AlyssaR** [comment]
Good catch! This has been resolved on our dev branch. Changes probably won't be merged to master yet, though. Thanks, @jrutz
