### ISSUE TITLE
View Group Button.... doesn't do anything

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#171]
- Not logged in
- Searched something (anything that got results)
- Table shows view group button
- I can click it
- Nothing happens... except I can see that I clicked it
- I've clicked it a lot for fun, but I kind of always half expect there to be something happening 
  ![screen shot 2015-04-27 at 10 36 01 am](https://cloud.githubusercontent.com/assets/5313865/7351188/63ebf596-ecc9-11e4-80bf-712f3ce2c56d.png)

**Comment by quincyschurr** [comment]
You're right, it should bring you to the group profile page. Thanks for pointing this one out.

**Comment by AlyssaR** [comment]
@jrutz @quincyschurr Actually it should have been popping up telling you that you "Don't have permission" to view the page and redirecting you to home so you could login. I think this was tied to the API issue that was breaking account registration, so if you try again it should behave this way.
