### ISSUE TITLE
(Nitpicky) Search lets you search for nothing

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#172]
This could probs be solved with a quick check before sending the request - Results in an empty search set. 

![screen shot 2015-04-27 at 10 38 50 am](https://cloud.githubusercontent.com/assets/5313865/7351250/bcff6320-ecc9-11e4-8c97-c2ad11b87467.png)

**Comment by quincyschurr** [comment]
@jrutz fixing this so that you are told that no results are found on the page if you do not enter anything into the Search box.

**Comment by aakashpatel1** [comment]
@jrutz, I am unable to produce the same results you had.
