### ISSUE TITLE
Create Account Email Validation

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#173]
This was the only thing I could find regarding the create account validation (though a little sad I can't do it in Russian and I have met exactly one person who has a single letter as a first name)
![screen shot 2015-04-27 at 11 08 42 am](https://cloud.githubusercontent.com/assets/5313865/7351972/3c691b02-ecce-11e4-8582-af8209d1a32f.png)

**Comment by KristoforHorst** [comment]
completed and closed by @AlyssaR
