### ISSUE TITLE
Invalid Login System

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#175]
(I think) I created an account. And I'm bad with passwords, but my password is password. 
![screen shot 2015-04-27 at 11 22 32 am](https://cloud.githubusercontent.com/assets/5313865/7352243/13580f0a-ecd0-11e4-95f4-af613493e9a1.png)
![screen shot 2015-04-27 at 11 22 18 am](https://cloud.githubusercontent.com/assets/5313865/7352249/1514b4d8-ecd0-11e4-9cf5-b2040c06d2da.png)

**Comment by AlyssaR** [comment]
@jrutz Can you attempt to duplicate this issue again? Apologies, but I think this was tied to another API issue. Also, I'm sorry but you'll probably need to register first, because we cleared the database. Thanks!
