### ISSUE TITLE
Adding Organization won't add, no error message

### ISSUE THREAD

**Issue by KristoforHorst** [AlyssaR/StudyNetwork#176]
Using the string "Gen Erick's Org" as an example, the add organization button does not add the organization to the list but no error alert shows. 

![image](https://cloud.githubusercontent.com/assets/7100924/7354667/75d31a6e-ece2-11e4-84a4-222117c0559a.png)

**Comment by AlyssaR** [comment]
Need to add validation/prompt. The issue is using the apostrophe. Should have same "illegal characters" as creating a group. @KristoforHorst @quincyschurr

**Comment by AlyssaR** [comment]
This is tied to Issue #45 . The reason it's not giving an error is because that field is vulnerable to SQLi. Self-assigning since I have the other issue already.

**Comment by AlyssaR** [comment]
This is resolved on the branch byeBobbyTables. I am not merging to dev yet, because I'm also using that branch to sanitize all other inputs from SQLi as well.
