### ISSUE TITLE
We only had 99 issues. 

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#192]
Solution: now we have 100 closed.

**Comment by AlyssaR** [comment]
![friends-laugh](https://cloud.githubusercontent.com/assets/6731550/7362257/b71328d6-ed2b-11e4-9e8c-72c1460811db.gif)

**Comment by KristoforHorst** [comment]
Second

**Comment by aakashpatel1** [comment]
Pretty colors....

**Comment by Ma1iciousL0af** [comment]
....And this ain't one?

**Comment by cknee217** [comment]
I want more FRIENDS!

**Comment by KristoforHorst** [comment]
I'll be your friend.

**Comment by Ma1iciousL0af** [comment]
WEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE

**Comment by AlyssaR** [comment]
![not even sorry](https://cloud.githubusercontent.com/assets/6731550/7362261/d848508a-ed2b-11e4-9371-0ddc930e7b78.gif)

**Comment by quincyschurr** [comment]
_laughs in chair hysterically_

**Comment by KristoforHorst** [comment]
Who is hungry?

**Comment by AlyssaR** [comment]
I guess we can close this now? 

![joey-tribianni-shrug-friends](https://cloud.githubusercontent.com/assets/6731550/7362265/e5e43ab0-ed2b-11e4-959b-f4030e3bb470.gif)

**Comment by Ma1iciousL0af** [comment]
Nevaaaaaar

**Comment by aakashpatel1** [comment]
Yo yo Fontebro

**Comment by AlyssaR** [comment]
Fontenot: "K bye."

![bye now](https://cloud.githubusercontent.com/assets/6731550/7362272/fc67e6a6-ed2b-11e4-860e-f00f0cae9bc6.gif)

**Comment by aakashpatel1** [comment]
Shhh... Jesus Loves you...

**Comment by KristoforHorst** [comment]
I can confirm that this issue is resolved.

**Comment by aacarroll** [comment]
LAST

**Comment by KristoforHorst** [comment]
I can confirm that this issue is resolved.  @aacarroll Wants the last laugh.

**Comment by Ma1iciousL0af** [comment]
@KristoforHorst And I got it. 

Yeah you do. :octopus:
