### ISSUE TITLE
Adding pre-existing class doesn't give verbose error

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#199]
When adding a class that already exists, the prompt just says "Class added successfully." For consistency with other prompts (i.e. Organization) it maybe should say "[Notice] Class already exists. You've been added to the existing class." or something? 
@quincyschurr @cknee217 @KristoforHorst @aacarroll @aakashpatel1

**Comment by quincyschurr** [comment]
I got this

**Comment by KristoforHorst** [comment]
closed by timeout, not important?
