### ISSUE TITLE
Search by Group connected to class

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#201]
Get the redirect button for this to work on the profile.html page

**Comment by quincyschurr** [comment]
API done and button appears on site. Kash is working on JS redirect

**Comment by quincyschurr** [comment]
This works. @aakashpatel1 you can close this

**Comment by quincyschurr** [comment]
Except we just need to merge it

**Comment by AlyssaR** [comment]
Merged
