### ISSUE TITLE
Validation Commented Out?

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#206]
In js/validate.js the validFName and validLName functions are commented out so they always return one thing. This shouldn't be the case, but I'm not sure who changed it. Can others please verify that this should be fixed? / Fix it? 

@KristoforHorst @quincyschurr @aacarroll @aakashpatel1 

Thanks

**Comment by aakashpatel1** [comment]
Sorry, I had commented it out. This function is breaking our create a class form. It is being called to validate the name of the Professor, however, the id attributes don't match up. I'll fix this ASAP.

**Comment by KristoforHorst** [comment]
resolved and completed. closed
