### ISSUE TITLE
Should the home page show my classes and groups?

### ISSUE THREAD

**Issue by williamoconnor** [AlyssaR/StudyNetwork#22]
What is the use of creating classes and groups?

**Comment by AlyssaR** [comment]
For this iteration, we just put in the functionality to add classes/groups to the database/your profile. Next iteration we will have a "view profile" page where you can see your classes and groups. The purpose of them is so you can join/create study groups based on the classes you have added to your profile. Also once our search page is finished, you'll be able to see the groups that everyone has created. 

Does that answer your question?

**Comment by AlyssaR** [comment]
Closing question.
