### ISSUE TITLE
Iteration 1 username and password bar issue

### ISSUE THREAD

**Issue by oklaiss** [AlyssaR/StudyNetwork#23]
Contact info:
Owen Klaiss
oklaiss@smu.edu

User registration, login and logout work as expected. However when inputing the username or password there is an issue with the username and password fields not auto-clearing when you click on them. This bug occurs every time.
![screen shot 2015-03-22 at 5 27 28 pm](https://cloud.githubusercontent.com/assets/8547458/6771818/f782fcaa-d0b8-11e4-9539-7ebb40b20bd0.png)

**Comment by KristoforHorst** [comment]
Changed the value in field to be a placeholder, should now correctly clear.
