### ISSUE TITLE
[Story 2] Student ID Format Validation (lack thereof)

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#24]
There is validation for an SMU email address, but not for the id itself. It allows you to successfully register with an invalid ID 100% of the time upon creating an account. 

SMU ID numbers are (as far as I know) 8 numerals without exception. 
![screen shot 2015-03-22 at 9 57 58 pm](https://cloud.githubusercontent.com/assets/5313865/6773418/f3153ec8-d0de-11e4-9c9a-89a3e136aca9.png)

**Comment by KristoforHorst** [comment]
Added form validation for the register page, opened new issue for password enhancement.
