### ISSUE TITLE
[Story 2] Email Validation/User Validation Bugs

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#27]
Frequency: 100%
Allows a user to register with only the email "@smu.edu" 

A user may register multiple time with the same email if there are extra spaces.
![screen shot 2015-03-22 at 10 15 07 pm](https://cloud.githubusercontent.com/assets/5313865/6773612/8bdeda7c-d0e1-11e4-82a6-dfc0b72be3e5.png)
![screen shot 2015-03-22 at 10 15 58 pm](https://cloud.githubusercontent.com/assets/5313865/6773614/8efbec90-d0e1-11e4-9c4b-fb8e610dcbd3.png)
![screen shot 2015-03-22 at 10 16 46 pm](https://cloud.githubusercontent.com/assets/5313865/6773616/91ec21fe-d0e1-11e4-9a8f-7a16161504ae.png)

**Comment by KristoforHorst** [comment]
Must have a minimum of one character, no longer accepts spaces.
