### ISSUE TITLE
Make it pretty

### ISSUE THREAD

**Issue by Ma1iciousL0af** [AlyssaR/StudyNetwork#58]
Yeah... GUI needs an overhaul. :)

**Comment by Ma1iciousL0af** [comment]
Just finished the bootstrap stuff for all but profile.html. Color to come tomorrow :)

**Comment by AlyssaR** [comment]
This is subjective but is it safe to say this midgoal was done? Or do you still need to "add color"? @aacarroll

**Comment by Ma1iciousL0af** [comment]
Yes, @KristoforHorst created a separate issue for color.

**Comment by AlyssaR** [comment]
@aacarroll Closing because bootstrap was installed.
