### ISSUE TITLE
Guest Users Get Pulled Through "View Profile" Screen

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#69]
Rather than being given an initial error message
![screen shot 2015-04-13 at 11 03 07 am](https://cloud.githubusercontent.com/assets/5313865/7119826/7d20c0c4-e1ce-11e4-84df-22945d24a617.png)

**Comment by AlyssaR** [comment]
@jrutz am I understanding this issue correctly as some links should be disabled/hidden for guests/users not logged in? (Then of course if they manually type in the URL have an error that kicks them off.) Or did you mean something else?

**Comment by jrutz** [comment]
Spot on.

**Comment by AlyssaR** [comment]
Great! Thanks, @jrutz! 

@aakashpatel1 I will start working on this, although if it gets too confusing and GUI-like then I might ask you for help. Just a heads up.

**Comment by AlyssaR** [comment]
@aakashpatel1 @quincyschurr or @cknee217 Can someone pull the bugfixes branch and see if you can do the following steps in Chrome and maybe in Safari? It works for me in Firefox but not in Chrome, and I can't tell why. Want to see if it's just me. 
- Click Login
- Login (crazy right)
- Click Home
- Click Login

--> Expected (and seen in Firefox): Redirect to Home
--> Potential Error (in Chrome, maybe Safari?): ... Nada.

**Comment by AlyssaR** [comment]
To do: 
- Make login link change to edit/view profile after login
- Make redirect/block for guests be less abrupt and have error messages
- Find a way to do it other than onload()?

**Comment by AlyssaR** [comment]
Done.
