### ISSUE TITLE
Error Message/Error Consistency

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#71]
It does start with a capital letter (further testing revealed you want a capital letter then at least one lower case letter, but it was never specified through messages)
![screen shot 2015-04-13 at 11 05 17 am](https://cloud.githubusercontent.com/assets/5313865/7119862/c8330900-e1ce-11e4-820b-a8c729e4fc09.png)
Teacher's first name?
![screen shot 2015-04-13 at 11 09 57 am](https://cloud.githubusercontent.com/assets/5313865/7119896/feb6edfc-e1ce-11e4-88b4-7b63f8ce35b8.png)
Same deal as in Registration - There is at least one capital letter so I don't know what you want
![screen shot 2015-04-13 at 11 07 11 am](https://cloud.githubusercontent.com/assets/5313865/7119887/edc931bc-e1ce-11e4-84a7-4b58b58b4089.png)

I don't know what this is trying to tell me (I can guess at the first one, but not at the second)
![screen shot 2015-04-13 at 11 11 35 am](https://cloud.githubusercontent.com/assets/5313865/7119925/21ec30ca-e1cf-11e4-95f9-b3628225f896.png)
![screen shot 2015-04-13 at 11 11 39 am](https://cloud.githubusercontent.com/assets/5313865/7119927/26317708-e1cf-11e4-892d-e3b227213505.png)

**Comment by AlyssaR** [comment]
Error messages on names is updated. 
Pop up showing time entered removed.
Pop up showing error type (last screenshot) removed. 

Please verify @quincyschurr @cknee217

**Comment by quincyschurr** [comment]
@AlyssaR just grammar errors on the pop up now. Seems to be working how we want.

**Comment by quincyschurr** [comment]
Need to change message when wrong email or password is entered for the login. Currently says [object][Object]

**Comment by AlyssaR** [comment]
@quincyschurr where are the grammar errors you're seeing?

**Comment by AlyssaR** [comment]
Found and fixed grammar error.
