### ISSUE TITLE
Time Validation

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#72]
Automatically sets the time to midnight if it can't find an equivalent time
![screen shot 2015-04-13 at 11 11 02 am](https://cloud.githubusercontent.com/assets/5313865/7120116/59141c42-e1d0-11e4-8dac-88214c171d11.png)
![screen shot 2015-04-13 at 11 11 11 am](https://cloud.githubusercontent.com/assets/5313865/7120118/5b5ed26c-e1d0-11e4-9bef-a4309f220e32.png)

**Comment by quincyschurr** [comment]
@jrutz - try opening up our website in Chrome. The time input is of data type time and that is only supported in certain browsers. I haven't found a way around that yet.

**Comment by jrutz** [comment]
You're right, it does work in Chrome. 
It does not work in Firefox or Safari.

Maybe try giving the user a suggested format and then regex against that? (like in the spirit of mm/dd/yyyy or hh/mm)

**Comment by quincyschurr** [comment]
@AlyssaR @aakashpatel1 @cknee217 would you mind taking a look at the createClassForm and createStudyGroupForm and see if you as a user would understand the time format when inputting time in the Safari or Firefox browser?

**Comment by AlyssaR** [comment]
@quincyschurr @aakashpatel1 @cknee217 
Don't have Safari so tested in Firefox. Format makes sense, however it doesn't seem to allow lowercase AM/PM (which is a likely input). I'd recommend uppercasing it post-input to catch that? 

Note: If I'm wrong about the "view all groups" section showing the time in military time then this may not be an issue.

**Comment by quincyschurr** [comment]
@AlyssaR yes I was going to try to convert it to 12 hour time in an issue for iteration 4. Also, not sure how I would validate the time to uppercase because the input type for this is a time data type... Any ideas?

**Comment by AlyssaR** [comment]
@quincyschurr as suggested by testing team members, we can just switch it to text and make sure we validate well?

**Comment by quincyschurr** [comment]
@AlyssaR Then we need to re-think the database because the SQL data type is time and the reason we used the time data type in html is because they talk to each other due to the same formatting.

**Comment by AlyssaR** [comment]
@quincyschurr there's a Javascript function to convert strings to datetime objects. Taking this issue for now. If I can't fix it, will push to iteration 4.

**Comment by AlyssaR** [comment]
To do:
- Add description of proper form of input data for users. see "create group" for example.
- Use Javascript to convert string. Verify this takes care of input such as: 01:00:00, 1:00:00, 1:00

**Comment by quincyschurr** [comment]
Validated. Just need to push database to dev
