### ISSUE TITLE
Editing Profile - Name Validation

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#74]
This could be optional if you want to let people get swag with their names, but it could cause difficulties if you ever want to search for people
![screen shot 2015-04-13 at 11 07 26 am](https://cloud.githubusercontent.com/assets/5313865/7120193/eb612a4a-e1d0-11e4-8b52-8cce78bb8a86.png)
![screen shot 2015-04-13 at 11 07 44 am](https://cloud.githubusercontent.com/assets/5313865/7120196/f02d3c1c-e1d0-11e4-9537-f7e5f70198bf.png)

(this has been mentioned in another issue but is also relevant on the editing profile page)
![screen shot 2015-04-13 at 11 06 54 am](https://cloud.githubusercontent.com/assets/5313865/7120210/087c20b2-e1d1-11e4-9ce7-24e05c22e77b.png)

**Comment by quincyschurr** [comment]
Ready for testing before I close this!! @AlyssaR @aacarroll @cknee217

**Comment by AlyssaR** [comment]
What branch? @quincyschurr

**Comment by quincyschurr** [comment]
@AlyssaR dev!!! Sorry, I promise I didn't try to break things if I did...

**Comment by AlyssaR** [comment]
Verified it works!
