### ISSUE TITLE
Editing Profile - Can't Change Email

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#75]
Attempted this with ~8 addresses
![screen shot 2015-04-13 at 11 36 28 am](https://cloud.githubusercontent.com/assets/5313865/7120253/656889c8-e1d1-11e4-9c28-919b1b0246b5.png)
![screen shot 2015-04-13 at 11 36 32 am](https://cloud.githubusercontent.com/assets/5313865/7120255/66d61e1a-e1d1-11e4-8dc4-0640a5aa9b8a.png)

**Comment by AlyssaR** [comment]
Error was in API function. Resolved and tested in Chrome and Firefox. 

@cknee217 or @quincyschurr could one of you check this in Safari as well just to be safe?

**Comment by AlyssaR** [comment]
Verified by @quincyschurr in Safari. Closing
