### ISSUE TITLE
Easy to Bypass Validation System

### ISSUE THREAD

**Issue by jrutz** [AlyssaR/StudyNetwork#76]
(this is super nitpicky as I don't think most people would mess with this, but you can use the JS command line to bypass all the regulations for registration/editing)

![screen shot 2015-04-13 at 11 46 16 am](https://cloud.githubusercontent.com/assets/5313865/7120454/ec544f20-e1d2-11e4-8dde-d818d4a8d5db.png)

**Comment by AlyssaR** [comment]
Appreciate this, @jrutz! I was aware of a similar issue, however had not resolved it yet. Important because it may also allow a login bypass. 

Will be resolved in iteration 3. Thanks for finding!

**Comment by KristoforHorst** [comment]
closed by timeout
