### ISSUE TITLE
Utilize Classes Through Profile

### ISSUE THREAD

**Issue by williamoconnor** [AlyssaR/StudyNetwork#77]

**Comment by quincyschurr** [comment]
@williamoconnor We are hoping to implement this feature so that a user can add the classes they are in and filter a search for study groups based on those classes.

**Comment by AlyssaR** [comment]
Need to minimally add functionality to view added classes from profile. @aakashpatel1 would you prefer to do this or should I? (It should be similar to viewing added groups from profile, so not too much new code)

As time permits also allow these classes to link to searches for study groups with that class as the search term.

**Comment by quincyschurr** [comment]
API functionality in there, working on JS for this.
