### ISSUE TITLE
[7] Join study groups

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#8]
Join previously created study groups (as non admin)
- Join a study group based on uid, gid, and role. Get the uid from the session, and the gid from group data that is already pulled to the profile. Role will automatically be "member"

**Comment by quincyschurr** [comment]
@aakashpatel1 okay, all the functionality that I think needs to be there is there, except that I may need to return something different it you need it. Right now it just returns a success, but I can change that so it returns the user's id or whatever if you want to give a message when they add it. It's under the joinStudyGroup branch and function is called joinStudyGroup

**Comment by quincyschurr** [comment]
Do we want to display all group members in group Profile page?

**Comment by quincyschurr** [comment]
@aakashpatel1  everything should be there for you to do to JS for this functionality

**Comment by quincyschurr** [comment]
The API for this is there. Closing, just waiting on JS functionality
