### ISSUE TITLE
[13] Search by organization

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#81]

**Comment by AlyssaR** [comment]
@cknee217 @quincyschurr duplicated issue. just reassigning.

**Comment by quincyschurr** [comment]
this can be closed as soon as we have JS confirmation of it

**Comment by quincyschurr** [comment]
This works, just need to bug fix it... So moving to bug now.

**Comment by KristoforHorst** [comment]
Closed and completed - no issue description and apparent resolution.
