### ISSUE TITLE
[13] Create Organization infrastucture

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#82]
Similar to what is available for joining study groups. Need to have the user be able to input organizations they are involved in on campus. API call must have a check to see if that oid exists in the database of Organizations.

**Comment by quincyschurr** [comment]
Should be working (all functionality thus far is in the API). Just waiting to test with JS

**Comment by quincyschurr** [comment]
Update: working on creating all the JS for this. Should be able to close soon.
