### ISSUE TITLE
[x] Android App

### ISSUE THREAD

**Issue by AlyssaR** [AlyssaR/StudyNetwork#84]
Because our users obviously want to study on the go...

**Comment by KristoforHorst** [comment]
Installed Android Studio, I think it's the right environment to develop in. Going to spend some time trying to mess around in it and figure out what I'm doing, make sure I can emulate on my computer or if I need to port to my actual phone (Android Galaxy S5).

**Comment by KristoforHorst** [comment]
Created a new repo for this at: http://www.github.com/KristoforHorst/StudyNetwork-Android

Have initial commit with beginnings of a login-page activity and a profile page activity.
Issues with:
[:octopus:] login's password field saying that password is too short, believe it's a regex issue.
[:octopus:] On successful login, moving to profile activity page (don't know how to do this, currently  resolving) - swapping views in general
[] Unsure of how to hook API to application, specifically login validation in database, registration for new accounts in database, and profile/study group retrieval from database. need @AlyssaR to help in person with these
[] Unsure of what pages should be created for native application
[] not enough sodium in the application, should be saltier.
[:octopus:] no one is reading this far down
[] General TODOs that are documented in code

4/19/2015 9:50 PM CST

**Comment by KristoforHorst** [comment]
^^ I tried to make a list and it didn't work. /sigh :octopus:

**Comment by KristoforHorst** [comment]
Successful login should now move the user to the profile activity page.

All login attempts are successful - no password is required. I'm not sure why this is allowing no-pass login authentication. - Resolved 4/19/2015 10:57 

4/19/2015 10:43. Committing now as well

**Comment by AlyssaR** [comment]
Found out this isn't due til iteration 4. Moving.

**Comment by KristoforHorst** [comment]
Closing for great justice. Confirmed by @aacarroll. Woot woot.
