### ISSUE TITLE
Join Study Group

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#87]
Allows user to join a study group

1.) on the groupProfile html page we need a button to let the users add themselves. JavaScript function call needs to connect to the API. There is nothing that needs to be sent to it via text box or anything. It is just a button

**Comment by quincyschurr** [comment]
@aakashpatel1 creating a branch for this functionality

**Comment by quincyschurr** [comment]
Update: Just waiting on the JavaScript for this one.

**Comment by AlyssaR** [comment]
Wrote javascript for this one.
