### ISSUE TITLE
24 Hour time to 12-hour

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#89]
Convert the time data type to show up as 12-hour on pages.

**Comment by aakashpatel1** [comment]
@quincyschurr, could you please further elaborate on what you mean by "12-hour on pages?"

**Comment by quincyschurr** [comment]
@aakashpatel1 if you add a study group, you can add the time with AM/PM and then load the editProfile.html page, the meeting time for the group shows up in 24-hour standard time. I'm just going to convert it to AM/PM for displaying.

**Comment by aakashpatel1** [comment]
@quincyschurr, Thanks!

**Comment by quincyschurr** [comment]
Have been playing around with this. May take out time data type and reformat database to reflect a regex varchar input so this works on Safari and the like, not just Chrome.

**Comment by quincyschurr** [comment]
Update: Works as well. Just need to push database update later
