### ISSUE TITLE
Toggle edit profile to view profile

### ISSUE THREAD

**Issue by aakashpatel1** [AlyssaR/StudyNetwork#92]
"Edit profile" button should Toggle to between "edit profile" and "view profile". For edit profile, the page should allow user to edit their profile information. The "view profile" button should allow users to view their profile without input buttons.

**Comment by AlyssaR** [comment]
@aakashpatel1 This is also done! 
![happy](https://cloud.githubusercontent.com/assets/6731550/7307497/e4c6a44e-e9d2-11e4-9f8a-c0cb3af11375.jpg)
