### ISSUE TITLE
Display search results

### ISSUE THREAD

**Issue by aakashpatel1** [AlyssaR/StudyNetwork#93]
Create a search results page that displays the name of the study group, the associated class, and the meeting time.

**Comment by AlyssaR** [comment]
This works @aakashpatel1 . Close it. Enjoy the victory you have earned. 
![high five](https://cloud.githubusercontent.com/assets/6731550/7307556/2e2ad1f0-e9d3-11e4-8247-a6ce7ec2ea7f.gif)
