### ISSUE TITLE
"Search by" dropdown menu

### ISSUE THREAD

**Issue by aakashpatel1** [AlyssaR/StudyNetwork#94]
Create a dropdown menu which allows users to search by either organization, class, and group name.

**Comment by quincyschurr** [comment]
@aakashpatel1 - if this is referring to searching for study group, I think they can also search by class and group name (not professor though). @AlyssaR can you confirm?

**Comment by aakashpatel1** [comment]
@quincyschurr @AlyssaR, the issue has been updated. Thanks for the heads up.

**Comment by cknee217** [comment]
right now we only have functionality for groups by name and class. If we want to be able to search by anything else we need to get more information from the user in their profile.

Sent from my iPad

On Apr 14, 2015, at 10:19 PM, quincyschurr <notifications@github.com<mailto:notifications@github.com>> wrote:

@aakashpatel1https://github.com/aakashpatel1 - if this is referring to searching for study group, I think they can also search by class and group name (not professor though). @AlyssaRhttps://github.com/AlyssaR can you confirm?

##

**Comment by quincyschurr** [comment]
@aakashpatel1 yeah, major is not a thing right now. Organizations are so maybe hold off on the majors until we see if we have time to do so. Thanks!

**Comment by AlyssaR** [comment]
@aakashpatel1 I think you can close this.
![thumbs up](https://cloud.githubusercontent.com/assets/6731550/7307472/bfdf581a-e9d2-11e4-8cfb-f5fc9a2f2ae3.gif)

**Comment by AlyssaR** [comment]
Reopening so Kash can close it

**Comment by aakashpatel1** [comment]
@AlyssaR, your GIFS are priceless...
