### ISSUE TITLE
Leave study group button

### ISSUE THREAD

**Issue by aakashpatel1** [AlyssaR/StudyNetwork#96]
Allow users to remove study group from user profile in "edit profile" mode.

**Comment by quincyschurr** [comment]
@aakashpatel1 Can we also put this button on the groupProfile page too?

**Comment by quincyschurr** [comment]
@aakashpatel1 this button and functionality works only from the groupProfile page, not on the profile page.

**Comment by aakashpatel1** [comment]
Got it. I will transfer it to the groupProfile.html

**Comment by quincyschurr** [comment]
No it's in the groupProfile.html but not in the profile.html

**Comment by aakashpatel1** [comment]
@quincyschurr 
1. groupProfile.html [y/n]?
2. profile.html [y/n]?

**Comment by quincyschurr** [comment]
It is already on groupProfile.html
It does not work on profile.html

**Comment by quincyschurr** [comment]
Works
