### ISSUE TITLE
Avoid duplicate Organizations

### ISSUE THREAD

**Issue by quincyschurr** [AlyssaR/StudyNetwork#98]
In the JavaScript, when the user is inputting a name for an Organization they are involved in can we validate that the first letter is capitalized and then the remaining are all lowercase? This is how I am going to test to see if the Organization already exists from another User's input that way I can enroll all users to the same organization which in turn will help with searching.

It's hard to do string manipulation in SQL but not impossible. Anyone else have ideas on how to go about this.

**Comment by AlyssaR** [comment]
In accounts.js there is a function called validFName(). This should do what you're wanting though I would copy it to a new function like validOrgName() that allows spaces, since names obviously shouldn't have multiple words in one.

**Comment by quincyschurr** [comment]
Believe I did this. There is a valid Org function, should work just like validName

**Comment by AlyssaR** [comment]
@quincyschurr please clarify if this issue is for not allowing users to create new orgs with same name or for validating that their new org name is allowed.

**Comment by quincyschurr** [comment]
This is for seeing if Users are not creating two Organizations of the same name but being added to the enrollment table. Org name is already done with Regex verification.

**Comment by AlyssaR** [comment]
I already added a condition so if they try to add an organization that exists, they are enrolled and notified that the group already exists. At some point it'd be good to add a "suggested similar names" thing, but that's probalby beyond our scope at this point. Closing.
